import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';

test('real shared dispatch honors Ask/Off/Plan, persists artifacts and replays without generation', async t => {
  const home = await fs.mkdtemp(path.join(os.tmpdir(), 'minnow-image-e2e-'));
  process.env.MINNOW_HOME = home;
  const { resetMinnowHomeCache } = await import('../../server/config/home.js'); resetMinnowHomeCache();
  t.after(async () => { resetMinnowHomeCache(); delete process.env.MINNOW_HOME; await fs.rm(home, { recursive: true, force: true }); });
  const { writeConfigJson } = await import('../../server/config/store.js');
  const { createProvider } = await import('../../server/providers/store.js');
  const { registerImageAdapter } = await import('../../server/image-generation/adapter-registry.js');
  const { executeServerTool } = await import('../../server/runtime/tools-middleware.js');
  const workspace = path.join(home, 'project'); await fs.mkdir(workspace);
  const bytes = await sharp({ create: { width: 16, height: 12, channels: 3, background: 'blue' } }).png().toBuffer();
  let submissions = 0;
  registerImageAdapter({ id: 'fixture', capabilities: () => ({ operations: ['generate'], options: { format: ['png'] } }), catalog: async () => [{ id: 'fixture-model' }], generate: async () => { submissions++; return { bytes, mime: 'image/png', usage: null, cost: null }; } });
  await createProvider({ id: 'image-fixture', label: 'Fixture', baseUrl: 'https://fixture.example.test', apiKind: 'openai-v1', enabled: true });
  await writeConfigJson('config.json', { imageGeneration: { enabled: true, providerId: 'image-fixture', adapterId: 'fixture', modelId: 'fixture-model' } });
  const options = { workspaceRoot: workspace, modeId: 'build', executionIdentity: 'run/tool' };
  await writeConfigJson('tools.json', { permissions: { default: { generate_image: 'ask' } } });
  assert.match((await executeServerTool('generate_image', { prompt: 'fish' }, options)).result, /requires approval/);
  await writeConfigJson('tools.json', { permissions: { default: { generate_image: 'off' } } });
  assert.match((await executeServerTool('generate_image', { prompt: 'fish' }, options)).result, /disabled/);
  await writeConfigJson('tools.json', { permissions: { default: { generate_image: 'full' } } });
  assert.match((await executeServerTool('generate_image', { prompt: 'fish' }, { ...options, modeId: 'plan' })).result, /Plan mode/);
  assert.equal(submissions, 0);
  const info = JSON.parse((await executeServerTool('image_generation_info', { check_connection: true }, options)).result);
  assert.equal(info.status, 'Ready'); assert.equal(submissions, 0);
  const result = await executeServerTool('generate_image', { prompt: 'fish', output_path: 'assets/fish.png' }, options);
  assert.ok(!result.result.startsWith('Error:'), result.result);
  const job = JSON.parse(result.result);
  assert.equal(job.status, 'succeeded'); assert.equal(submissions, 1);
  assert.equal(result.attachments[0].generated.path, 'assets/fish.png');
  assert.ok(!result.attachments[0].url.includes('token='));
  assert.deepEqual(await fs.readFile(path.join(workspace, 'assets/fish.png')), bytes);
  const replay = JSON.parse((await executeServerTool('generate_image', { prompt: 'fish', output_path: 'assets/fish.png' }, options)).result);
  assert.equal(replay.jobId, job.jobId); assert.equal(submissions, 1);
  const stored = JSON.parse((await executeServerTool('image_generation_info', { job_id: job.jobId }, options)).result);
  assert.equal(stored.status, 'succeeded'); assert.ok(!JSON.stringify(stored).includes('base64'));
  const other = path.join(home, 'other'); await fs.mkdir(other);
  assert.match((await executeServerTool('image_generation_info', { job_id: job.jobId }, { ...options, workspaceRoot: other })).result, /^Error:/);
  const changedApproval = await executeServerTool('generate_image', { prompt: 'fish' }, { ...options, executionIdentity: 'new', imageApproval: { approved: true, fingerprint: 'old-binding' } });
  assert.match(changedApproval.result, /binding changed/); assert.equal(submissions, 1);
  assert.match((await executeServerTool('generate_image', { prompt: 'fish', output_path: '../outside.png' }, { ...options, executionIdentity: 'escape' })).result, /^Error:/);
  assert.equal(submissions, 1);
  let release;
  const wait = new Promise(resolve => { release = resolve; });
  registerImageAdapter({ id: 'slow-fixture', capabilities: () => ({ operations: ['generate'], options: {} }), catalog: async () => [{ id: 'fixture-model' }], generate: async () => { submissions++; await wait; return { bytes, mime: 'image/png' }; } });
  await writeConfigJson('config.json', { imageGeneration: { enabled: true, providerId: 'image-fixture', adapterId: 'slow-fixture', modelId: 'fixture-model' } });
  const controller = new AbortController();
  const pending = executeServerTool('generate_image', { prompt: 'fish' }, { ...options, executionIdentity: 'cancel-late', abortSignal: controller.signal });
  while (submissions < 2) await new Promise(resolve => setTimeout(resolve, 5));
  controller.abort(); release();
  const canceled = JSON.parse((await pending).result);
  assert.equal(canceled.status, 'canceled'); assert.deepEqual(canceled.artifacts, []);
  assert.deepEqual(await fs.readdir(path.join(workspace, 'assets')), ['fish.png']);
  await executeServerTool('generate_image', { prompt: 'fish' }, { ...options, executionIdentity: 'cancel-late' });
  assert.equal(submissions, 2);
});
