#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const vendor = join(root, 'src/styles/vendor/uicons');
const used = new Set();
function scan(path) {
  if (path === vendor) return;
  for (const entry of readdirSync(path, { withFileTypes: true })) {
    const file = join(path, entry.name);
    if (entry.isDirectory()) scan(file);
    else if (/\.(ts|css|html|md)$/.test(entry.name)) collect(readFileSync(file, 'utf8'));
  }
}
function collect(text) {
  for (const match of text.matchAll(/\bfi-(?:rr|sr)-[a-z0-9-]+/g)) used.add(match[0]);
}
scan(join(root, 'src'));
collect(readFileSync(join(root, 'index.html'), 'utf8'));
// Preserve every previously available glyph for persisted custom issue icons.
for (const style of ['regular', 'solid']) {
  collect(readFileSync(join(root, 'node_modules/@flaticon/flaticon-uicons/css', style, 'rounded.css'), 'utf8'));
}
for (const style of ['regular-rounded', 'solid-rounded']) {
  const css = readFileSync(join(vendor, `${style}.css`), 'utf8');
  const filtered = css.replace(/\.(fi-(?:rr|sr)-[a-z0-9-]+):before\s*\{[^}]*\}/g,
    (rule, name) => used.has(name) ? rule : '');
  writeFileSync(join(vendor, `${style}.used.css`),
    '/* Generated by scripts/sync-uicons.mjs; do not edit. */\n' + filtered.replace(/\n\s*\n/g, '\n'));
}
console.log(`Synced Uicons 4.0.0 CSS for ${used.size} referenced icons.`);
