import assert from 'node:assert/strict';
import { test, mock } from 'node:test';
import { Window } from 'happy-dom';
import { emptyLedger, recordTokenUsage } from '../../src/usage/token-ledger.ts';
import type { Chat } from '../../src/types.ts';

const chat = { id: 'chat', name: 'Example chat', tokenLedger: emptyLedger() } as Chat;
recordTokenUsage(chat, { source: { kind: 'main', modeId: 'build' }, providerId: 'local', modelId: 'example', usage: { prompt_tokens: 10, completion_tokens: 20 }, costUsd: null });
const otherChat = { id: 'other', name: 'Other workspace', tokenLedger: emptyLedger() } as Chat;
recordTokenUsage(otherChat, { source: { kind: 'main', modeId: 'build' }, providerId: 'local', modelId: 'other', usage: { prompt_tokens: 100, completion_tokens: 200 }, costUsd: 1 });
const unassignedChat = { id: 'unassigned', name: 'Unassigned', tokenLedger: emptyLedger() } as Chat;
recordTokenUsage(unassignedChat, { source: { kind: 'main', modeId: 'build' }, providerId: 'local', modelId: 'unassigned', usage: { prompt_tokens: 1, completion_tokens: 2 }, costUsd: null });
let confirmed = false;
const saved: string[] = [];
mock.module('../../src/ui/app-dialog.ts', { namedExports: { appConfirm: async () => confirmed } });
let workspace = '/example';
let resolveServer: (value: boolean) => void;
mock.module('../../src/config/storage-mode.ts', { namedExports: { isServerStorageMode: () => true } });
mock.module('../../src/tools/client.ts', { namedExports: { detectLocalServer: () => new Promise<boolean>(resolve => { resolveServer = resolve; }) } });
mock.module('../../src/state/sessions.ts', { namedExports: { scheduleSaveSessions: ({ chatId }: { chatId: string }) => saved.push(chatId), getActiveChat: () => chat, getChatsSortedByUpdatedDesc: () => [chat, otherChat, unassignedChat], getChatsForWorkspace: () => workspace ? [chat] : [] } });
mock.module('../../src/state/workspace.ts', { namedExports: { getWorkspacePath: () => workspace } });
mock.module('../../src/ui/settings-controls.ts', { namedExports: { appendSettingsOfflineHint: () => {} } });
const { renderUsageSettingsSection } = await import('../../src/ui/settings-usage.ts');

test('Usage renders before discovery, switches scope, and distinguishes missing prices', async () => {
  const win = new Window();
  const previous = { document: globalThis.document };
  Object.assign(globalThis, { document: win.document });
  try {
    document.body.innerHTML = '<div id="settingsUsageBody"></div>';
    const pending = renderUsageSettingsSection();
    assert.match(document.body.textContent!, /Total usage/);
    assert.match(document.body.textContent!, /Not priced/);
    assert.equal(document.querySelectorAll('[role="table"] [role="cell"]').length, 4);
    const breakdown = document.querySelector<HTMLSelectElement>('#usageBreakdown')!;
    breakdown.value = 'model';
    breakdown.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.equal(document.querySelector('[role="table"]')?.getAttribute('aria-label'), 'Usage by model');
    assert.equal(document.querySelectorAll('.usage-chart__bar').length, 1);
    assert.match(document.querySelector('.usage-breakdown')!.textContent!, /retained completions/);
    assert.match(document.querySelector('.usage-breakdown')!.textContent!, /other \(local\)/);
    breakdown.value = 'source';
    breakdown.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.match(document.querySelector('.usage-chart svg').getAttribute('aria-label'), /333 tokens/);
    const select = document.querySelector<HTMLSelectElement>('#usageScope')!;
    assert.deepEqual(Array.from(select.options, option => option.textContent), ['Total', 'Workspace', 'Current chat']);
    const tokenTotal = () => document.querySelectorAll('.usage-instrument__value')[1]?.textContent;
    assert.equal(tokenTotal(), '333');
    select.value = 'chat';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.match(document.body.textContent!, /Current chat usage/);
    assert.equal(tokenTotal(), '30');
    select.value = 'workspace';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.match(document.body.textContent!, /Workspace usage/);
    assert.equal(tokenTotal(), '30');
    assert.equal(document.querySelectorAll('.usage-instrument').length, 1);
    workspace = '';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.match(document.body.textContent!, /Choose a workspace/);
    assert.equal(document.querySelectorAll('.usage-instrument').length, 0);
    select.value = 'total';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.equal(tokenTotal(), '333');
    const reset = document.querySelector<HTMLButtonElement>('.usage-reset')!;
    const clickReset = async () => {
      reset.click();
      await new Promise(resolve => setTimeout(resolve, 0));
    };
    await clickReset();
    assert.equal(tokenTotal(), '333', 'cancel keeps usage');
    assert.deepEqual(saved, []);
    workspace = '/example';
    select.value = 'workspace';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    confirmed = true;
    await clickReset();
    assert.equal(chat.tokenLedger!.totals.totalTokens, 0);
    assert.equal(otherChat.tokenLedger!.totals.totalTokens, 300);
    assert.equal(unassignedChat.tokenLedger!.totals.totalTokens, 3);
    assert.deepEqual(saved, ['chat']);
    assert.equal(reset.disabled, true);
    select.value = 'chat';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    assert.equal(reset.hidden, true);
    select.value = 'total';
    select.dispatchEvent(new win.Event('change') as unknown as Event);
    await clickReset();
    assert.equal(otherChat.tokenLedger!.entries.length, 0);
    assert.equal(unassignedChat.tokenLedger!.totals.totalTokens, 0);
    assert.deepEqual(saved, ['chat', 'chat', 'other', 'unassigned']);
    assert.equal(reset.disabled, true);
    resolveServer!(true);
    await pending;
  } finally {
    Object.assign(globalThis, previous);
    await win.happyDOM.close();
  }
});
